"""'add'

Revision ID: 8bd1d0fadad7
Revises: fbcb37559c13
Create Date: 2020-11-17 17:04:44.975497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd1d0fadad7'
down_revision = 'fbcb37559c13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ih_house_facility', sa.Column('aa', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ih_house_facility', 'aa')
    # ### end Alembic commands ###
