"""'delete'

Revision ID: cc15b2119d02
Revises: 8bd1d0fadad7
Create Date: 2020-11-17 17:05:56.975985

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc15b2119d02'
down_revision = '8bd1d0fadad7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ih_house_facility', 'aa')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ih_house_facility', sa.Column('aa', mysql.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
